apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: progapws-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-alias: progapws.policiacivil.go.gov.br
spec:
  tls:
    - hosts:
        - progapws-homo.policiacivil.go.gov.br
        - progapws.policiacivil.go.gov.br
      secretName: certificado-pc
  rules:
    - host: progapws-homo.policiacivil.go.gov.br
      http:
        paths:
          - path: /
            backend:
              serviceName: progapws-service
              servicePort: http
